id: A18ECED48
title: Prayer to Khandro Tsering Chödrön
type: translation
pechas:
- I1EE1741B
- ID38C55E9
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:48:48.238050
  last_modified_at: 2023-01-04 12:48:48.238075
  collections:
  - Khandro Tsering Chödrön Series
  - Works of Tibetan Masters
alignment_to_base:
  I1EE1741B/22D4: 879B
  ID38C55E9/CCA7: 879B
